version: '3.8'

services:
  ysservices-angular:
    image: mycompanyname/ysservices-angular:latest
    container_name: ysservices-angular
    build:
      context: ../../../
      dockerfile: angular/Dockerfile.local
    ports:
      - "4200:80"
    depends_on:
      - ysservices-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network

  ysservices-api:
    image: mycompanyname/ysservices-api:latest
    container_name: ysservices-api
    hostname: ysservices-api
    build:
      context: ../../
      dockerfile: src/ysservices.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=8da6f3b7-cf53-4885-a0b5-bff48ce1038e
      - App__SelfUrl=https://localhost:44354
      - App__AngularUrl=http://localhost:4200
      - App_CorsOrigins=http://localhost:4200
      - App__HealthCheckUrl=http://ysservices-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44354
      - App__RedirectAllowedUrls=http://localhost:4200
      - App__MVCPublicUrl=https://localhost:44306
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=ysservices;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44354:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  

  ysservices-web-public:
    image: mycompanyname/ysservices-web-public:latest
    container_name: ysservices-web-public
    build:
      context: ../../
      dockerfile: src/ysservices.Web.Public/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=8da6f3b7-cf53-4885-a0b5-bff48ce1038e
      - App__SelfUrl=https://localhost:44306
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__IsContainerized=true      
      - RemoteServices__Default__BaseUrl=http://ysservices-api
      - AuthServer__Authority=https://localhost:44354/
      - AuthServer__MetaAddress=http://ysservices-api
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=ysservices;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44306:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network  
  db-migrator:
    image: mycompanyname/ysservices-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/ysservices.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__ysservices_App__RootUrl=http://localhost:4200
      - OpenIddict__Applications__ysservices_Swagger__RootUrl=https://localhost:44354
      - OpenIddict__Applications__ysservices_Web_Public_Tiered__RootUrl=https://localhost:44306
      - OpenIddict__Applications__ysservices_Web_Public__RootUrl=https://localhost:44306
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=ysservices;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network    
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network  
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      

volumes:
  sqldata:
    name: ysservices_sqldata
networks:
  abp-network:
    name: ysservices-network
    driver: bridge
